export const APP_ROUTER = {
    INDEX: "/",
    HOME: "/home",
    COMPONENT: "/component",
    BOOKING: "/booking",
    AUTH: "auth",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    CHANGE_PASSWORD: "change-password",
    REFRESH_TOKEN: "/auth/accessToken-generate",
    HOTELDETAIL: "/hotel-detail",
    TIMELINE: "/timeline",
    BOOKINGDETAILS: "/booking-details",
    ALLROOM: "/all-rooms",
};
