export const APP_ROUTER = {
    INDEX: "/",
    HOME: "/home",
    COMPONENT: "/component",
    BOOKING: "/booking",
    HOTELDETAIL: "/hotel-detail",
    ORDER: "/order",
    ORDERDETAIL: "/order/order-detail",
    PAYMENT: "/order/payment",
    INFO: "/order/info",
    AUTH: "auth",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH_TOKEN: "/auth/accessToken-generate",
    USER: "/user",
    CHANGE_PASSWORD: "/user/change-password",
    // BOOKINGDETAILS: "/user/booking-details",
    ORDERSCUSTOMER: "/user/orders/customer",
    ADMIN: "/admin",
    TIMELINE: "/admin/timeline",
    ALLROOM: "/admin/all-rooms",
    LISTORDERS: "/admin/list-orders",
     BOOKINGDETAILS: "/admin/booking-details",
    ROOM: "/admin/rooms",
    HOTELREGISTER: "/user/hotel/register",
    SERVICES: "/admin/services",
    ROOMPRICE: "/admin/rooms/price",
};

export const QR = {
    BANK_ID : '970422',
    ACCOUNT_NO : '0398246147',
    TEMPLATE : 'compact',
    ACCOUNT_NAME :'NGUYEN PHUC',
    CHECK: 'https://script.googleusercontent.com/macros/echo?user_content_key=nrQmJAXY3C65E444SQyR9_qhmyI_mmEtnEvAlz9CdTlQs_7Bh12WcnnCi8hYaZ_S7Rl6krEUUQZSseM3RlQtC5k8BwrjnHj7m5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnLm_cYW7z27iITyVm9XL5u87hoyOzFejjw-2jjY15ZuQ-3IO3HyfHio2WVIx030jptd_YD2AefuWuAd5NfVxP76Iua2smjMi_g&lib=MEgBQXox1O-dq5nqj_sjaShMrWCC0QGP_'
}
